version: '3.9'

services:
  db_api:
    container_name: db_api
    image: postgres:15
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - db_api:/db_api
      - api_node_modules:/db_api/node_modules

volumes:
  db_api: {}
  api_node_modules: {}
