version: '3.9'
services:
  db_api:
    container_name: db_api
    image: postgres:15
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_DB_NAM$:  ${POSTGRES_DB_NAME}F
    ports:
    - ${PORT}:${PORT}
    
volumes: {}

