name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t kimsnow/apartments-app .
      - name: Publish image to docker hub
        run: docker push kimsnow/apartments-app:latest

  deploy:
    needs: build
    runs-on: ip-172-31-35-188

    steps:
      - name: Pull image from docker hub
        run: docker pull kimsnow/apartments-app:latest
      - name: Delete old container
        run: docker rm -f apartments-app-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name apartments-app-container kimsnow/apartments-app
